### ISSUE TITLE
How to solve the problem of "zero kld!!!"?

### ISSUE THREAD

**Issue by zhangming-19** [wyu-du/GP-VAE#1]
When I am trying to train the t5-gpave, there is a problem of "zero kld!!!".
![20220420102353](https://user-images.githubusercontent.com/87935248/164134351-9e550ede-d8fe-4645-9a33-a916473835ee.png)
Also, the "zero kld!!!" is also in the training of the LSTM-based variational encoder-decoder with GP priors.
Thank you for your help and I am looking forward to hearing from you.

**Comment by wyu-du** [comment]
Hi, 

This message occurs when the inverse of the covariance matrix in the GP prior cannot be calculated, which is in this [line](https://github.com/wyu-du/GP-VAE/blob/main/models/t5/t5_gpvae.py#L107). 
In this implementation, we simply skip such training examples during training and print out the "zero kld!!!" message as a warming.

Thanks,
Wanyu

**Comment by zhangming-19** [comment]
Thank you for your kind help~
