### ISSUE TITLE
inference speed and diversity

### ISSUE THREAD

**Issue by kiaia** [wyu-du/GP-VAE#8]
Hi!
Thanks for your great work! I'm working on getting results on another paraphrase dataset under  T5 + GP prior setting.  I have the following two questions:
* I found that the generation speed is relatively slow due to the inference batch size 1,  and something get wrong if I change it. Is there any way to speed up the generation?
* if I want to get a trade-off between quality and diversity, is it suitable to set the scalar to 7 just like it used in the paper for the paraphrasing task?

**Comment by wyu-du** [comment]
Hi,

Thanks for your interest in our work!
- If you want to increase the batch size during generation, you need to change the decode() function [here](https://github.com/wyu-du/GP-VAE/blob/main/models/t5/t5_gpvae.py#L501) to decode_batch() function (documentation [here](https://huggingface.co/docs/tokenizers/api/tokenizer#tokenizers.Tokenizer.decode_batch)).
- Yes, you can freely tune the scalar until you find the best quality and diversity trade-off on the dev set. In our experiments, we find setting the scalar to 7 gives the best result.

**Comment by kiaia** [comment]
Hi.
Thanks for your detailed reply. I have sped up the generation process!
